### ISSUE TITLE
Trying to use as a lib

### ISSUE THREAD

**Issue by anirjoshi** [FlorentAvellaneda/EvalMaxSAT#3]
When I try to compile using `g++` the `main.cpp` program. I see the following error
```
main.cpp:6:10: fatal error: EvalMaxSAT.h: No such file or directory
    6 | #include "EvalMaxSAT.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.

```

Then after locating the EvalMaxSAT.h in `lib/EvalMaxSAT/src` directory, and replacing the header with `#include "lib/EvalMaxSAT/src/EvalMaxSAT.h"`, I encounter another error:
```
In file included from main.cpp:6:
lib/EvalMaxSAT/src/EvalMaxSAT.h:9:10: fatal error: communicationlist.h: No such file or directory
    9 | #include "communicationlist.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Do we have to manually correct paths of all headers or am I missing something? (I am a bit new to looking into large software systems) Thanks a lot!

**Comment by FlorentAvellaneda** [comment]
The project uses cmake. You can compile in the following way:
`mkdir build
cd build
cmake ..
make`
Then to execute :
`./EvalMaxSAT_bin --help`

**Comment by anirjoshi** [comment]
After adding a line `std::cout << "SOME RANDOM STRING\n";` at the start of the main function in main.cpp, and executing the above commands, I am unable to see the output! Thanks!

**Comment by anirjoshi** [comment]
Ok! I changed the `CMakeLists.txt` file. Added the following and it seems to work with this!

```
add_executable (main main.cpp)

	target_link_libraries(main
	    ${LIB_LINK}
	)
```
Thanks!
