### ISSUE TITLE
Multicore Capabilities

### ISSUE THREAD

**Issue by na3na3na** [FlorentAvellaneda/EvalMaxSAT#6]
Hi,

You mentioned in your short description that a multicore version of EvalMaxSAT was already implemented although disabled. How do i go able re-enabling/ using the multicore version?

Side note: What does the first number in the output that follows the first o represent?  Using the example you provided, it would be the 1844...1615. I know the 2 represents the cost of the solution (sum of weights of the unsat clauses)

```
> $ ./EvalMaxSAT_bin log.8.wcsp.log.wcnf 
> o 18446744073709551615
> o 2
> s OPTIMUM FOUND
> v 00100101010011111
> c Total time : 0.00165765s
```

Thanks!

**Comment by FlorentAvellaneda** [comment]
Hi,

Ah yes, sorry. I probably deactivate it directly in the source code for MSE2022... The easiest way would be to recompile from the sources on version 440bf90

```
> git clone https://github.com/FlorentAvellaneda/EvalMaxSAT.git
> cd EvalMaxSAT
> git checkout 440bf90
> mkdir build
> cd build
> cmake ..
> make
> ./EvalMaxSAT_bin -p 4 log.8.wcsp.log.wcnf
```
